version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8900:443"
    volumes:
      - ./backend:/var/www/web
    depends_on:
      - php
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/web
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/mysql/lib:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql
      - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    